-- Insert real test products into database
-- First, ensure we have a system user
INSERT INTO users (id, email, password, name, role, "tokenBalance", plan, "createdAt", "updatedAt")
VALUES ('system', 'system@lonaat.com', 'system', 'System', 'admin', 0, 'free', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Insert test products
INSERT INTO products (id, "userId", name, description, price, "affiliateLink", category, source, tags, images, "isActive", featured, views, clicks, "createdAt", "updatedAt")
VALUES 
  (
    'prod-1',
    'system',
    'Smart Wireless Earbuds Pro',
    'Premium wireless earbuds with active noise cancellation, 30-hour battery life, and crystal-clear sound quality. Perfect for music lovers and professionals.',
    79.99,
    'https://example.com/affiliate/earbuds-pro',
    'Electronics',
    'JVZoo',
    ARRAY['electronics', 'audio', 'wireless'],
    ARRAY['https://placehold.co/400x300/0066cc/white?text=Earbuds+Pro'],
    true,
    true,
    0,
    0,
    NOW(),
    NOW()
  ),
  (
    'prod-2',
    'system',
    'Ultimate Marketing Course 2024',
    'Complete digital marketing masterclass with 200+ video lessons, templates, and tools. Learn SEO, social media marketing, email campaigns, and more.',
    197.00,
    'https://example.com/affiliate/marketing-course',
    'Education',
    'WarriorPlus',
    ARRAY['marketing', 'education', 'business'],
    ARRAY['https://placehold.co/400x300/ff6600/white?text=Marketing+Course'],
    true,
    true,
    0,
    0,
    NOW(),
    NOW()
  ),
  (
    'prod-3',
    'system',
    'AI Content Generator Suite',
    'Revolutionary AI-powered content creation tool. Generate blog posts, social media content, ad copy, and more in seconds. Includes 50+ templates.',
    47.00,
    'https://example.com/affiliate/ai-content-gen',
    'Software',
    'JVZoo',
    ARRAY['ai', 'content', 'software', 'automation'],
    ARRAY['https://placehold.co/400x300/9933ff/white?text=AI+Content+Gen'],
    true,
    false,
    0,
    0,
    NOW(),
    NOW()
  ),
  (
    'prod-4',
    'system',
    'Facebook Ads Mastery Blueprint',
    'Step-by-step guide to creating profitable Facebook ad campaigns. Includes case studies, templates, and advanced targeting strategies.',
    97.00,
    'https://example.com/affiliate/fb-ads-mastery',
    'Marketing',
    'WarriorPlus',
    ARRAY['facebook', 'ads', 'marketing', 'social-media'],
    ARRAY['https://placehold.co/400x300/3b5998/white?text=FB+Ads+Mastery'],
    true,
    false,
    0,
    0,
    NOW(),
    NOW()
  ),
  (
    'prod-5',
    'system',
    'E-commerce Empire Builder',
    'Complete system for building a profitable online store. Includes supplier connections, marketing strategies, and automation tools.',
    127.00,
    'https://example.com/affiliate/ecommerce-empire',
    'Business',
    'JVZoo',
    ARRAY['ecommerce', 'business', 'dropshipping'],
    ARRAY['https://placehold.co/400x300/00cc66/white?text=Ecommerce+Empire'],
    true,
    false,
    0,
    0,
    NOW(),
    NOW()
  ),
  (
    'prod-6',
    'system',
    'SEO Domination Toolkit',
    'Professional SEO tools and training to rank #1 on Google. Includes keyword research, backlink analysis, and rank tracking.',
    67.00,
    'https://example.com/affiliate/seo-toolkit',
    'Software',
    'WarriorPlus',
    ARRAY['seo', 'tools', 'software', 'marketing'],
    ARRAY['https://placehold.co/400x300/ff3366/white?text=SEO+Toolkit'],
    true,
    false,
    0,
    0,
    NOW(),
    NOW()
  ),
  (
    'prod-7',
    'system',
    'YouTube Money Machine',
    'Learn how to build a profitable YouTube channel from scratch. Includes monetization strategies, video templates, and growth hacks.',
    87.00,
    'https://example.com/affiliate/youtube-money',
    'Education',
    'JVZoo',
    ARRAY['youtube', 'video', 'education', 'monetization'],
    ARRAY['https://placehold.co/400x300/ff0000/white?text=YouTube+Money'],
    true,
    false,
    0,
    0,
    NOW(),
    NOW()
  ),
  (
    'prod-8',
    'system',
    'Crypto Trading Masterclass',
    'Master cryptocurrency trading with proven strategies. Includes technical analysis, risk management, and portfolio building.',
    157.00,
    'https://example.com/affiliate/crypto-trading',
    'Finance',
    'WarriorPlus',
    ARRAY['crypto', 'trading', 'finance', 'investment'],
    ARRAY['https://placehold.co/400x300/f7931a/white?text=Crypto+Trading'],
    true,
    false,
    0,
    0,
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  "affiliateLink" = EXCLUDED."affiliateLink",
  category = EXCLUDED.category,
  source = EXCLUDED.source,
  tags = EXCLUDED.tags,
  images = EXCLUDED.images,
  "updatedAt" = NOW();
