
import DashboardLayout from "@/layouts/DashboardLayout";
import AIToolCard from "@/components/AIToolCard";
import AIStatusPanel from "@/components/AIStatusPanel";
import AIDashboardPanel from "@/components/AIDashboardPanel";

export default function AIDashboard() {
  // Mock data
  const aiTools = [
    { name: "Campaign Generator", description: "Automate campaign creation with AI.", status: "Active" },
    { name: "Product Discovery AI", description: "Find top products using AI insights.", status: "Active" },
    { name: "Traffic Optimizer", description: "Optimize traffic and conversions.", status: "Inactive" },
  ];
  const aiStatus = [
    { title: "AI Engine", status: "Online", details: "All systems operational." },
    { title: "Last Automation Run", status: "Online", details: "2 hours ago" },
    { title: "API Usage", status: "Online", details: "1,200 calls this month" },
  ];
  const aiPanels = [
    { title: "Automated Campaigns", value: "12", description: "Campaigns generated by AI" },
    { title: "AI Recommendations", value: "34", description: "Product suggestions this week" },
    { title: "Traffic Optimizations", value: "5", description: "Active optimizations" },
  ];
  return (
    <DashboardLayout>
      <h1 className="text-2xl font-bold mb-6">AI Automation</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {aiPanels.map((p) => (
          <AIDashboardPanel key={p.title} {...p} />
        ))}
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {aiTools.map((t) => (
          <AIToolCard key={t.name} {...t} />
        ))}
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {aiStatus.map((s) => (
          <AIStatusPanel key={s.title} {...s} />
        ))}
      </div>
      <button className="px-4 py-2 bg-blue-600 text-white rounded">Configure New AI Tool</button>
    </DashboardLayout>
  );
}
