"""Add commission enhancements

Revision ID: 2755813623ff
Revises: dbd9ab2a386b
Create Date: 2025-12-18 04:07:01.203228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2755813623ff'
down_revision = 'dbd9ab2a386b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_commissions_external_ref'), ['external_ref'], unique=False)
        batch_op.create_foreign_key(None, 'ad_boosts', ['campaign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_commissions_external_ref'))
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
