"""Add production models for email verification, password reset, imported products, and commissions

Revision ID: 51239f50ee30
Revises: 
Create Date: 2025-11-13 20:09:19.797112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51239f50ee30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transactions_reference'))
        batch_op.create_index(batch_op.f('ix_transactions_reference'), ['reference'], unique=False)

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requested_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_created_at'))
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_requested_at'), ['requested_at'], unique=False)
        batch_op.create_foreign_key(None, 'bank_accounts', ['bank_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])
        batch_op.drop_column('flutterwave_reference')
        batch_op.drop_column('method')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('account_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_details', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('flutterwave_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_requested_at'))
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('requested_at')
        batch_op.drop_column('bank_account_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_reference'))
        batch_op.create_index(batch_op.f('idx_transactions_reference'), ['reference'], unique=False)

    # ### end Alembic commands ###
