"""Add imported_product_id to ad_boosts

Revision ID: 56bff84dfaf9
Revises: 2755813623ff
Create Date: 2025-12-18 05:02:24.786450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bff84dfaf9'
down_revision = '2755813623ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_boosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('boost_type', sa.String(length=50), nullable=True, server_default='manual'))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_ad_boosts_imported_product_id'), ['imported_product_id'], unique=False)
        batch_op.create_foreign_key(None, 'imported_products', ['imported_product_id'], ['id'])

    op.execute("UPDATE ad_boosts SET boost_type = 'manual' WHERE boost_type IS NULL")
    
    with op.batch_alter_table('ad_boosts', schema=None) as batch_op:
        batch_op.alter_column('boost_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_boosts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ad_boosts_imported_product_id'))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('boost_type')
        batch_op.drop_column('imported_product_id')

    # ### end Alembic commands ###
