"""Add real estate and AI system tables

Revision ID: dbd9ab2a386b
Revises: 51239f50ee30
Create Date: 2025-12-17 19:49:33.868889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd9ab2a386b'
down_revision = '51239f50ee30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_admin_audit_action'))
        batch_op.drop_index(batch_op.f('idx_admin_audit_admin_id'))
        batch_op.drop_index(batch_op.f('idx_admin_audit_created_at'))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('priority_boost',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('commission_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('commission_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('priority_boost',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('admin_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_admin_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_admin_audit_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_admin_audit_action'), ['action'], unique=False)

    # ### end Alembic commands ###
